README.md, megatron/data/indexed_dataset.py, tools/preprocess_data.py
by @Huu Nguyen - thank you!
Example:
```
python tools/preprocess_data.py \
--datasets \
meg-gpt2-oscar-en-500-p1_text_document \
meg-gpt2-oscar-en-500-p2_text_document \
meg-gpt2-oscar-en-500-p3_text_document \
--output-prefix meg-gpt2_oscar-combined \
--merge-file gpt2-merges.txt \
--vocab gpt2-vocab.json \
--dataset-impl mmap \
--tokenizer-type GPT2BPETokenizer
```
=> extend preprocess_data.py to support merging datasets

README.md, megatron/data/indexed_dataset.py, tools/merge_preprocessed_data.py, tools/preprocess_data.py
We clean up the scrip in order to obtain two scripts for two seperate flows.
=> Seperate merge script from process_data script

megatron/model/transformer.py, megatron/training.py
fork happened right after https://github.com/bigscience-workshop/Megatron-DeepSpeed/commit/b56b50bb4728ef72c8e3586f1c9f89558f542cae
This PR catches on 2 commits since then:
```
git cherry-pick 5be61ce7dccbd337f0c476b5979ab744c0af3eea
git cherry-pick e9d83dd1b295b6cc3dcfd7c25cb77a070153529c
```
New checkpoint is https://github.com/microsoft/Megatron-DeepSpeed/commit/370971d52149b3b34cf74df3f6079fc7837fb106 (didn't merge it as it was empty).
=> [microsoft/Megatron-DeepSpeed sync] Commits including Jul 26, 2021

megatron/training.py, pretrain_gpt.py
This PR catches on 1 commit:
```
git cherry-pick fc0113facc860a63322e7ef20b02cbd01f56fbf1
```
New checkpoint is microsoft/Megatron-DeepSpeed@fc0113f
=> [microsoft/Megatron-DeepSpeed sync] Commits including 2021-07-30

megatron/training.py
replaying @VictorSanh's https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/39/commits/f14e77286a896f0f294fd075cb2e4c2c8a32fdfe
with some tweaks to keep consistent for tr1-13B branch.
This should fix timers in tensorboard.
Thanks @VictorSanh
=> Log timers fix

requirements.txt
=> add missing dependencies

.github/workflows/ci.md, .github/workflows/main.yml, tests/README.md
This PR adds a CI, using a 4-gpu EC2 instance.
Huge, huge thanks to @philschmid who held my hand and helped me to set things up from scratch.
And big thanks to @jpalomaki who worked out the logic to help with EC2 not having enough instances at random times and suggesting a fault tolerance solution by trying 3 different sub-regions. It may still fail if all 3 don't have resources, but this is less likely to happen than taking chances with just one. The discussion thread is here: https://github.com/machulav/ec2-github-runner/issues/60
=> [CI] setting up a CI with EC2 backend

tools/convert_checkpoint/README.md, tools/convert_checkpoint/deepspeed_checkpoint.py, tools/convert_checkpoint/deepspeed_to_megatron.py, tools/convert_checkpoint/inspect_checkpoint.py, tools/convert_checkpoint/inspect_deepspeed_checkpoint.py
This PR catches on 1 commit:
```
git cherry-pick 1a74a0513441cf4
git push
```
New checkpoint is microsoft/Megatron-DeepSpeed@1a74a0513441cf4
=> [microsoft/Megatron-DeepSpeed sync] Commits including 2021-09-18

tools/convert_checkpoint/README.md, tools/convert_checkpoint/deepspeed_to_megatron.py, tools/convert_checkpoint/deepspeed_to_transformers.py
missed committing this in https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/110
additionally update README.md to explain the new script
=> add direct meg-ds to hf format script (part2)

.github/workflows/main.yml
`pull_request_target` doesn't checkout the right sha - restore `pull_request`
=> [ci] run on pull_request branch

megatron/arguments.py, megatron/model/language_model.py, megatron/optimizer/__init__.py, megatron/testing_utils.py, tests/ds_config.json, tests/test_training.py
Hello, this short PR is related with my experiments: (https://huggingface.slack.com/archives/C020GC81PQT/p1633744264181500).
=> [Feature] Porting bitsandbytes to meg-deepspeed

megatron/training.py
original fix: https://github.com/bigscience-workshop/Megatron-DeepSpeed/commit/b982e040fbf12f089115cde560f685f673de6eb1
=> Alternative fix to TP > 1

.github/workflows/main.yml, tests/test_training.py
- switch to a different instance type that's hopefully more available
- use all gpus in the main test
=> [CI] improvements

.github/workflows/main.yml
undoing the mistake from  https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/177
=> [CI] fix which tests get run

megatron/training.py
This PR removes the duplicated param size printing that was already happening in `get_model` and reformats the w/ and w/ embeds to include tp/pp rank and make things more compact and prints synced.
Until now these were intermixed with other unrelated messages, making these more difficult to grok.
the new look is all synced and on a 8 gpu replica:
```
Number of parameters: [tensor rank - pipeline rank] w/ and w/o embeddings:
[001-001] 12.5868B / 12.5868B
[001-002] 12.5868B / 12.5868B
[001-003] 13.2894B / 12.5869B
[001-000] 13.2893B / 12.5868B
[000-001] 12.5868B / 12.5868B
[000-002] 12.5868B / 12.5868B
[000-003] 13.2894B / 12.5869B
[000-000] 13.2893B / 12.5868B
```
=> param size printing revamp

megatron/arguments.py, megatron/model/glu_activations.py, megatron/model/gpt_model.py, megatron/model/utils.py, megatron/utils.py, pretrain_prefix_lm.py, tests/test_training.py
Reweight loss depending on their position. I'd suggest running this with `--loss-on-targets-only` (as we should rule this option out as the reason why our current model underperforms).
=> Reweighting strat for prefix lm

megatron/training.py
use the correct seqlen when CL is used.
=> tflops for CL

megatron/training.py
Reverts bigscience-workshop/Megatron-DeepSpeed#224
It was done earlier I missed the code
=> Revert "tflops for CL"

megatron/arguments.py, tests/test_training.py
I decided to work on it after there was inactivity on #214
I wasn't sure where to save the file, so I saved it in the current directory only. Since we have to use it to check the config separately, I thought of naming the file with current timestamp. I hope that's okay. Please let me know if any other changes are required for this!
=> save args to txt file

.gitignore, megatron/training.py, run.sh, run_bf16.sh, run_fp16.sh
This syncs with bf16 meg-ds branch: https://github.com/microsoft/Megatron-DeepSpeed/commits/olruwase/bf16 (not master)
```
git checkout -b meg-ds-sync-2022-02-21
git remote remove other
git cherry-pick 3704a0a0dadb40a97a3c273c59f30318c34a5af4
git cherry-pick 1be15dcb086f47e7847c10d378428a23250e7023
git cherry-pick ec6bcabd1f7cf59e5d2b19773770ca2623eedac9
```
and had to fix conflicts
=> [sync] bf16

README.md, start_fast.md
This quick instructions document contains 3 steps:
1. installing software
2. preparing data
3. running the script
This is useful if you need to ask someone to reproduce problems with `Megatron-Deepspeed`
=> [doc]  start-fast instructions

megatron/arguments.py, megatron/data/mlm_dataset.py
Some things I noticed when coding shared-t5.
=> Merge MLM too fast 2

megatron/model/fused_softmax.py, megatron/model/gpt_model.py, megatron/model/language_model.py, pretrain_gpt.py, tests/test_model.py
Fixes: #305 
When refactoring some code, I accidentally broke the notion of causal masking. I've fixed it + implemented a test to make sure we don't ever break it again
=> Fix causal attention mask
