megatron/tokenizer/tokenizer.py, tools/preprocess_data.py
This pull implements huggingface tokenizer into the pre-processing script.
=> Hf tok pipeline

megatron/arguments.py, megatron/global_vars.py
This allows the user to use HF tokenizers at training time, using the same preprocessing-time arguments as #2
=> HF tokenizers (on the training side)

megatron/training.py
Was getting:
```
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 132, in pretrain
= build_train_valid_test_data_iterators(
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 842, in build_train_valid_test_data_iterators
= build_train_valid_test_data_iterators(
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 842, in build_train_valid_test_data_iterators
assert args.train_samples is None, \
AssertionError: only backward compatiblity support for iteration-based training
```
on restart after a very short first run.
=> fix bug when restarting with no eval in round 1

megatron/data/indexed_dataset.py
Merges didn't take in account document ids (whatever they were used for). This PR fixes this. Maybe we should fix this upstream?
Small colab to check that merge or without merge should be the same
https://colab.research.google.com/drive/1haC-r0t0TnhYlx0y3j3yqXsYdNAjUv2A#scrollTo=7jAoQyI9A5D-
Thanks @ontocord for spotting the issue!
=> Fix inconsistent merge

tools/merge_preprocessed_data.py
indices merge takes much longer than the concat of data, so moving the end timer to the end.
=> [dataset merge] fix timing

pretrain_gpt.py
Suddenly the training won't work anymore with:
```
Traceback (most recent call last): 
File "pretrain_gpt.py", line 215, in <module>
pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 144, in pretrain
iteration = train(forward_step_func,
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 675, in train
train_step(forward_step_func,
File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 381, in train_step
loss = model[0].train_batch(data_iter=data_iterator)
File "/home/stas/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/engine.py", line 291, in train_batch
self._exec_schedule(sched)
File …
```
=> fix attn_mask

megatron/global_vars.py, megatron/training.py
As discussed in issue #38:
- I grouped the metrics into a few groups
- Added speed metrics (under `iteration-time`)
- Added the mapping iteration (or step) vs samples
A preview of the tensorboard on a dummy training can be found [here](https://tensorboard.dev/experiment/54F4T0NVREO5RbLhbIMPcQ).
=> Group tensorboard metrics

megatron/tokenizer/gpt2_tokenization.py, tools/preprocess_data.py
Note that this supprts LRU caching in Python3 only. In python2, the caching is removed from BPE altogether.
=> Add LRU cache, add faster tokenization

megatron/model/activations.py, tests/test_activations.py, tests/utils.py
This PR addresses #44. Specifically, it implements the following activation functions:
* LiGLU
* GEGLU
* ReGLU
* SwiGLU
Nomenclature-wise, Bilinear seems to be synonymous with LiGLU.
=> Add GLU variants

megatron/training.py, pretrain_gpt.py
This PR catches on 2 commits:
```
git cherry-pick 3123a2943173
git cherry-pick f0131ce0287f008d85101fd
```
New checkpoint is microsoft/Megatron-DeepSpeed@f0131ce028
=> [microsoft/Megatron-DeepSpeed sync] Commits including 2021-08-09

megatron/data/indexed_dataset.py, tools/preprocess_dataset_mpi.py
This is work in progress, but I'll post it early to get feedback.
This PR includes a few things at once.
Updates ``megatron/data/indexed_dataset.py`` to use ``numpy`` to compute sample offsets to improve speed while writing an index file.
- https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/48/commits/f68999f738160a6df414b100959bccef95d07bf0
- https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/48/commits/a456e484734df310930e3655afc935caebfe64a9 (fix needed in addition to above commit)
Adds a new ``tools/preprocess_dataset_mpi.py`` script:
- uses HuggingFace datasets as the source to build (.bin and .idx) input files for megatron
- uses MPI to distribute work via ``mpi4py`` to support multiple nodes
- ``--split`` option to name the HF dataset split name, defaults to …
=> use HuggingFace Datasets as source to build Megatron data files

megatron/arguments.py
This PR fixes help for `--rampup-batch-size`:
1. resolves warning:
```
megatron/arguments.py:402
/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/arguments.py:402: DeprecationWarning: invalid escape sequence \ 
'   --rampup-batch-size 16 8 300000 \ '
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
2. adds missing white spaces
=> fix arg help

megatron/data/indexed_dataset.py
This fixes an issue when computing the document index offset value when merging cached ``IndexedDataset`` files.  The problem was that ``offset`` is overwritten in the ``data_offset`` loop before it is used to adjust the document index values.
=> fix: doc_idx offset when merging indexed dataset files

tools/preprocess_dataset_mpi.py
This updates the index selection logic in a couple ways:
- switches from ``random.shuffle`` to ``numpy.random.shuffle`` (timed to be about 10x faster)
- replaces the broadcast with a scatter
The scatter is implemented in two ways.  The first uses a scatter collective.  The second writes the full list to a temporary file that is then read back by each process.
I suppose if the scatter collective seems to be reliable, the temporary file is not needed and could be dropped.  I've left it in there for now.
Update:
Decided to drop the scatter file to simplify the code.  I think the scatterv should be sufficient, and if not, it's easy to add the file method back.
=> shuffle index list with numpy, scatter list, use file for large lists

megatron/data/indexed_dataset.py
@stas00 and @thomasw21 , I introduced a bug while computing the pointers list with the switch to use numpy.  This fixes that.
Before submitting that previous PR, I remember double checking the resulting index files with ``cmp``.  I must have mistakenly checked two files that were both produced with the incorrect code.
So any mmap files produced since merging that last PR will have bad data.  Sorry about that!
=> urgent fix: exclusive scan computing pointers list

megatron/testing_utils.py, tests/test_activations.py
pytorch-1.10-to-be dropped the non-public API `torch.testing.assert_equal`, see: https://pytorch.org/docs/stable/testing.html
So this is a follow up to: https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/47 to make the tests work with pt-nightly.
I used
```
torch.testing.assert_close(liglu(self.x), expected, rtol=0.0, atol=0.0)
```
to replace the function that was removed.
Perhaps we can add a wrapper for `torch_assert_equal` in `testing_utils.py` instead? 
@jaketae
=> [testing] fixes for pt-1.10

megatron/arguments.py, tests/test_activations.py
fixes a circular import problem introduced by https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/69#discussion_r693544500
=> fix circular import

requirements.txt
as `setup.py` pulls this file into `install_requires` - we have to support both formats - that of `setup.py` and that of `pip -r requirements.txt`, so this PR makes it possible.
Thanks to SO thread: https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repository-as-a-dependency
=> [requirements] fix format

megatron/global_vars.py, requirements.txt
Currently CC generates a ton of warnings at run time - and not measuring all of carbon! - this PR is trying possible workarounds proposed in https://github.com/mlco2/codecarbon/pull/241
So adding:
```
misfire_grace_time = 3
measure_power_secs = 60
max_instances = 3
```
Also added a logger preamble so that we could tell which rank the warning comes from.
- changed the hardwired SHA in requirements.txt to https://github.com/mlco2/codecarbon/commit/e6c3863acafc0d3482f0c8f6d23ab884662c4727 hoping for 2.0 release soon.
=> [WIP] [codecarbon] sorting out CC warnings + logger preamble

megatron/data/Makefile
Addressing https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/96 this PR adds an assertion in `Makefile` if `python3-config` is not available.
=> check whether python3-config is available

.github/workflows/main.yml
It seems that PRs coming from forks don't get to access the aws secrets and the whole thing fails, so trying to use `pull_request_target` suggested here:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
Thanks to @philschmid for the suggestion
=> simplify the CI trigger

tests/test_model.py
- Related to: #52 
Test were failing because my local script to run tests set come env variables to mimick distributed setting.
I suggest using `Hide whitespace changes` to review the code.
=> Fix model tests

megatron/testing_utils.py
This PR 
- completes the `torch_assert_equal` wrapper to work with older pytorch version
- adds `torch_assert_close` wrapper
Fixes: https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/52#issuecomment-921176223
=> [tensor comparisons] support pt-1.8, add torch_assert_close

tools/convert_checkpoint/deepspeed_to_transformers.py
This PR extendes @tjruwase work here: https://github.com/microsoft/Megatron-DeepSpeed/pull/14 to support a direct conversion from Meg-DS checkpoint to HF Transformers checkpoint, bypassing the Meg-DS to Meg conversion stage.
I'm cheating and combining the 2 stages into one script importing code from both stages. i.e. the script needs the latest transformers master for this to work.
=> add direct meg-ds to hf format script

megatron/data/indexed_dataset.py, tests/test_preprocessing.py, tools/merge_preprocessed_data.py
This extends the ``merge_preprocessed_data.py`` script to optionally use a parallel merge.  It changes that script to assume a distributed launch if given ``--merge distributed``.
=> update merge_preprocessed_data to use distributed merge

megatron/arguments.py, megatron/enums.py, megatron/model/transformer.py
I've implemented ALiBi efficiently, by just modifying the matmul_result matrix in transformer.py 
On my hardware, with the pretrain_gpt.py example, ALiBi runs just as fast as sinusoidal and uses 20MB of extra memory (that is 0.2% of the total memory usage). 
I think this implementation could be made even more efficient by modifying the mask instead of matmul_result, but this would require modifying the cuda code in scaled_upper_triang_masked_softmax and I don't have that knowledge.
=> ALiBi Implementation

megatron/model/transformer.py
This PR is @corbyrosset's suggestion at how to overcome the 104B numerical instability we have been experiencing. Quoting:
Re: 104B instability (https://huggingface.slack.com/archives/C01NHER1JLS/p1632801340055000) One thing I've encountered before is how the self-attention is computed. E.g. this [line](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/c839a8aa30731f71b3738d56009be9668508e366/megatron/model/transformer.py#L303) shows that the norm_factor may be multiplied after the Query * Key matrix multiplication. If the dim of Q and K are very large, the output may blow up and the norm_factor won't be able to save it.
Proposal: move the norm_factor inward, so Q and K are scaled down before matrix multiply:
```
matmul_result = torch.baddbmm(
matmul_result, …
```
=> Corby's numerically more stable self attn version

tests/test_training.py
At times magatron fails to build kernels and doesn't remove the lock file, which makes subsequent runs hang - so make sure there is no lock when starting the testing
=> [testing] ensure no lock file is dropped

Makefile, pyproject.toml, requirements.txt, setup.cfg
This PR fixes #129 by implementing the following:
- Add `black` and `isort` to dependencies
- Add formatting `Make` command
- Add `pyproject.toml` and `setup.cfg` for consistent formatting options
=> Configure code style formatters

megatron/model/gpt_model.py, megatron/utils.py, tests/test_training.py
We want to start experimenting if we remove the loss mask.
Context: prefixlm trained on oscar performes poorly on shorter context.
The initial intuition was that this task would be too easy for the model as it know the future in the non causal region. However T5 author has shared that he ran it with this option. One of the intuition is that it regularises hidden states.
**Careful**: This is being merged on top of  https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/169
=> [PrefixLM] Allow prefix lm to run with loss on target only false

megatron/model/gpt_model.py, megatron/utils.py, tests/test_training.py
What deepspeed does (I think):
- sum microbatch losses across gradient_accumulations: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/pipe/engine.py#L671-L673
- average loss across DP: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/pipe/engine.py#L525-L527
What Megatron-DS does:
- averages all tokens trained on (selected via loss_masking) within microbatch (normalisation factor is the number of tokens trained on, `loss_mask.sum()`): https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/megatron/model/gpt_model.py#L167-L169
The issue is we have a high variance of tokens we train on (`loss_mask.sum()`) in prefixlm in micro batches compared to batches. Therefore the value changes a lot and by normalising with this value we lose …
=> [PrefixLM] Figuring out why prefix lm is doing poorly on short context

megatron/training.py
Previously curriculum learning for pipeline parallel case will also truncate the eval data, which is not preferred. This PR fixes the issue.
=> Full seqlen eval for CL+PP

.github/workflows/main.yml, megatron/arguments.py, megatron/training.py, tests/ds_config_cl.json, tests/test_training.py
=> Support skip iteration flag

megatron/arguments.py, megatron/mpu/layers.py, tests/test_training.py
Given that BNB's layernorm in `Embedding` is very likely to have a positive impact on training stability, add this feature so that we can use it w/o BNB.
To activate add `--embed_layernorm`
Ideally I'd have set it by default, but that would break any resuming training since it won't have the weights in the checkpoint.
@ibeltagy, @VictorSanh, @TevenLeScao
=> add layernorm in Embedding

megatron/model/bert_model.py, megatron/model/gpt_model.py, megatron/model/realm_model.py, megatron/model/transformer.py, megatron/optimizer/__init__.py, megatron/schedules.py, megatron/training.py, pretrain_bert.py, pretrain_t5.py, tasks/zeroshot_gpt/evaluate.py, tools/generate_samples_gpt.py
replaying https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/117 as I can't push into that branch to rebase it
We are trying to eliminate this issue:
```
ImportError: cannot import name 'print_rank_0' from partially initialized module 'megatron' 
(most likely due to a circular import) (.../megatron/__init__.py)
```
Fixes: https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/73
=> eliminate `megatron/model/__init__.py` to avoid circular import

megatron/microbatches.py
A PR to add a space between `times` and `data` (reading the error in a conversation, I thought `timesdata` was a variable name)
=> Add missing space

megatron/initialize.py
Remove the hardcoded `tcp://` `init_process_group` method so that we could use the latest pytorch elastic methods (pt-1.9+).
This PR syncs with Megatron-LM:
https://github.com/NVIDIA/Megatron-LM/blob/b31e1296354e979722627a6c4dedafe19b51fa97/megatron/initialize.py#L179-L183
Now you can launch with one of:
```
export LAUNCHER="deepspeed --num_gpus $N_GPUS --master_port $MASTER_PORT"
export LAUNCHER="python -u -m torch.distributed.run \
--nproc_per_node $N_GPUS \
--rdzv_endpoint $MASTER_ADDR:$MASTER_PORT \
--rdzv_backend c10d \
--max_restarts 0 \
"
export LAUNCHER="python -u -m torch.distributed.launch \
--nproc_per_node $N_GPUS \
--master_addr $MASTER_ADDR \
--master_port $MASTER_PORT \
"
```
the old one (last) still works, but it emits a warning, so best to adjust to the randevouz one.
=> elastic launcher compatible init_process_group

megatron/initialize.py, megatron/tokenizer/tokenizer.py, megatron/utils.py, pretrain_gpt.py
The current state of the framework is very poor when it comes to logging. Tens of thousands of lines of logs are logged when the process starts.
Additionally when training crashes it's extremely difficult to find the actual error with hundreds of processes overwriting each other's logs making it close to impossible to decipher the errors.
This PR will gradually attempt to reduce the useless replicated noise to the bare minimum and figure out how to make the actual error found quickly on crash. 
Also one essential config for everybody to start using is:
```
--log-level info \
--log-level-replica error \
```
so that you get all the info on the first process, but replicas remain silent unless there is an issue.
=> [WIP] dealing with multi-process noise

.github/workflows/main.yml, tests/test_training.py
Test that we can use `--partition-activations` (which shards activations and uses less gpu memory!)
Update: it only works with TP=2 or PP=2 - not both. Fails with TP=2 and PP=2.
So won't merge until this is fixed on the Deepspeed side.
Issue to track: https://github.com/microsoft/DeepSpeed/issues/1538
=> [test] `--partition-activations`

megatron/model/fused_softmax.py, tests/test_model.py, tests/test_training.py
- Fixes: #206
There seems to be no issues with cuda kernels, as tests pass locally.
=> Checking we use fused kernels to compute scaled masked softmax on prefix lm

megatron/training.py
Currently, the valid dataloaders accumulate the number of valid steps elapsed together: a single `args.consumed_valid_samples` counter is incremented for every dataset. This is an issue as each valid data sampler takes `args.consumed_valid_samples` as the elapsed valid steps to compare with the size of the dataset: it quickly grows bigger, which [breaks the data sampler initialization](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/megatron/data/data_samplers.py#L73).
As every validation dataset is evaluated on equally, this PR fixes that issue by passing the correct number of elapsed valid steps per valid dataset, which is an equal fraction of `args.consumed_valid_samples for each data sampler.
=> Fix consumed_valid_samples counting for several valid dataloaders

megatron/training.py
This PR adds 2 new TB graphs:
1. `iteration-time/samples per second` - shows throughput for the whole ensemble
2. `iteration-time/samples per second per replica` - shows throughput per replica
3. TFLOPs - a derivation of (2) with a constant multiplier
Please let me know if this is agreeable, or whether you'd like to propose some changes
Here is the manually plotted version of (1) y: `samples per second`. x = iterations.
So you'd know what to expect.
If `DP=1` the 2 graphs would be identical.
The 2nd one is handy when one needs to compare graphs that are run with a different DP degree. Especially if DP is changed from job to job in the same run.
The key insight here is you can see how with the BS size increase the pipeline becomes more efficient and thus the throughput increases.
Just want …
=> [TB] add throughput graphs

megatron/fused_kernels/layer_norm_cuda_kernel.cu
Megatron-DeepSpeed fails to build with pt-nightly https://github.com/pytorch/pytorch/issues/69746
This has been fixed in Megatron-LM - so backporting the fix here:
```
git checkout -b sync-thc
git remote add other https://github.com/NVIDIA/Megatron-LM
git cherry-pick 75e521a0603467bf5ec78b2175f5ca3dd56e9872
git cherry-pick 4831071c900df5901570984c28b9f907892ff632
git cherry-pick f1295380cf06b0475165fbcbd89fbd88e9fee84c
git commit
git push
```
=> [sync] replay layer_norm_cuda_kernel.cu fixes

megatron/fused_kernels/__init__.py
working on improving the CUDA extensions build.
1. support `TORCH_CUDA_ARCH_LIST` env var to compile for specific sets of archs, e.g. to pre-build for multiple archs of choice and support systems with more than a single gpu type:
```
TORCH_CUDA_ARCH_LIST="6.1 8.6" python ....
```
2. remove hardcoded archs which slow down the build, as each additional arch has to include more code in the object. It should be quite faster to build for a single arch.
Tested on JZ with pt-1.10 and pt-1.8.1
=> [CUDA extensions] improve build

megatron/training.py
This PR is trying to fix interleaved prints, like:
```
[003-008] 103.3651B / 103.3651B
[002-030] 103.3651B / 103.3651B[001-030] 103.3651B / 103.3651B
[001-022] 103.3651B / 103.3651B
[001-021] 103.3651B / 103.3651B
[003-017] 103.3651B / 103.3651B
[001-015] 103.3651B / 103.3651B[003-015] 103.3651B / 103.3651B[002-015] 103.3651B / 103.3651B
```
these all should be one column, but as you can see some of the processes of the same machine end up interleaving with other processes.
=> [logging] synced print

megatron/training.py
This PR fixes TFLOPs calculation which was missing `/1e3` and was reporting GFLOPs instead.
Thank you for investigating, @bhavitvyamalik!
Fixes: https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/221
=> fix tflops calculation

megatron/checkpointing.py
it appears that `--no-load-optim` was being silently ignored with `--deepspeed`. This PR implements it.
=> implement missing --no-load-optim support for deepspeed path

megatron/initialize.py
Once this is merged: https://github.com/microsoft/DeepSpeed/pull/1622 we can start using these new flags for less noisy ds_report output.
Perhaps may be let's wait till the new DS release after the merge so that it won't break anybody's runs.
=> [ds report] less noise

megatron/global_vars.py
this closes #235 by override the original `add_scalar` with `functools.partial` and add `new_style=True` arg to `add_scalar`
@stas00 Could you have a look as I can't a preprocessed dataset?
Thanks
=> enable new_style for add_scalar function for faster data format

megatron/global_vars.py
Fixes https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/237 for when pt<1.9
=> fix `add_scalar` for pt<1.9

megatron/training.py, tools/logs/rescale-logs.py, tools/logs/tb-rename-events.py, tools/logs/tb-rescale-scalars.py
Was in milliseconds, is now in seconds. Variable names and log strings
indicate the unit is supposed to be seconds.
To fix up old TensorBoard log files, see
https://gist.github.com/janEbert/e364da49d4757499a7cdd8e71ffaa9e8.
I can also include the script in the repository if desired – I followed @stas00's example of using a GitHub gist here.
Fix #236.
=> Fix throughput unit

megatron/initialize.py, megatron/training.py
As we have recently discovered there was a very subtle issue with [the optimizer that wasn't fully restored on resume](https://github.com/bigscience-workshop/bigscience/blob/master/train/tr8b-104B/chronicles.md#on-the-importance-of-saving-and-restoring-the-optimizer-step-counter). And it's possible that some spikes we have encountered were related to that. 
So I think it'd help to log resume events.
I'm thinking perhaps simply logging `world_size` once per run, which will also have a second use which will tell us if we switched to a higher or lower number of nodes and perhaps see some additional correlations there.
Since TB will end up creating a flat line and we won't see the restart events I came up with the following hack, where on restart it logs world_size, and then logs another step …
=> [TB] log restarts

megatron/arguments.py, megatron/training.py, megatron/utils.py, tests/test_training.py
Since SLURM doesn't allow one user to kill another user's SLURM job or cancel a job array, we need a way to be able to have the program abort itself quickly in situations where one user started a job and has gone away and the group needs to restart it.
So @slippylolo suggested we implement a kill-switch, which is what this PR does.
The two logical spots to insert checks are:
1. startup - to deal with job arrays
2. before each iteration of the train loop - to deal with the current run
Since multiple jobs use the same repo this kill switch can't be hardcoded, and thus each run needs to "arm" the kill switch and must use a unique path so that unintentionally other instances won't get killed.
To arm:
```
pretrain_gpt.py ... --kill-switch-path /tmp/kill-switch-tr11-200B-exp1
```
To trigger: …
=> implement kill switch

megatron/arguments.py, megatron/initialize.py
In those situations where we can't afford a training slowdown make sure that the program doesn't start until all the fused kernel constraints have been met.
this is of course an optional feature for when it's important.
To activate, add:
`--abort-on-unmet-fused-kernel-constraints`
=> implement --abort-on-unmet-fused-kernel-constraints

megatron/optimizer/__init__.py
This is a workaround for the crash when using `apex.optimizers.FusedAdam` on A100s with 80GB. 
Currently can only load half the gpu memory, if I try to pack just a tad more over 40Gb this happens:
```
terminate called after throwing an instance of 'c10::CUDAError'
what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from query at /opt/conda/conda-bld/pytorch_1644999004077/work/aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x14b6eefe8ead in /gpfswork/rech/six/commun/conda/py38-pt111/lib/python3.8/site-packages/t …
```
=> [apex FusedAdam] crash workaround

megatron/training.py
Replace approximate with more precise TFLOPs formula (borrowed from Equation 3 in Section 5.1 of https://arxiv.org/pdf/2104.04473.pdf).
So now BS's TFLOPs can be compared to the ones reported by NVIDIA.
=> Replace approximate formula with exact one for throughput

megatron/arguments.py
this PR adds support for:
```
--train-weighted-split-paths-path /gpfswork/rech/six/commun/code/tr8b-104B/Megatron-DeepSpeed/data/train-splits.txt     
--valid-weighted-split-paths-path /gpfswork/rech/six/commun/code/tr8b-104B/Megatron-DeepSpeed/data/valid-splits.txt     
--test-weighted-split-paths-path /gpfswork/rech/six/commun/code/tr8b-104B/Megatron-DeepSpeed/data/test-splits.txt  
```
since cmd line is limited to 128k and the contents of the above files are longer that that - so it fails to start.
=> Try to read the data path arguments directly from a file

megatron/arguments.py, megatron/model/gpt_model.py
This PR allows one to set `--pp-partition-method 'type:transformer|embed'` to consider embedding layers on par with transformer layers when partitioning over PP stages. For large 250k vocab which takes about the same amount of memory as the transformer block this allows to balance memory usage between all stages - w/o it pp rank 0 and -1 use much more gpu memory than other stages.
=> make partition_method configurable

pretrain_gpt.py
This improves the situation when the training crashes - the tb for the root cause is then nicely reported at the end of the log file
=> deploy elastic error handler

megatron/fused_kernels/scaled_masked_softmax.h, megatron/fused_kernels/scaled_masked_softmax_cuda.cu, megatron/fused_kernels/scaled_upper_triang_masked_softmax.h, megatron/model/fused_softmax.py
As flagged by @thomasw21 in https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/259 - in we have only synced part of the fused_kernels fixes applied to Megatron-LM here https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/151. 
I tried to track all the changes since then, but there are too many and often are mixed with other unrelated PRs, so how about we just sync the whole folder and other related files.
this PR is trying just that.
I have no idea how to track all the individual contributors across many PRs, but I think it was primarily @hyunwoongko  so it should be easy to push him in as a contributor:
```
git commit --author "hyunwoongko <gusdnd852@naver.com>" -am "author attribution" --allow-empty
```
and it will be so once this is squash-merged.
=> sync the whole Meg-LM fused_kernels sub-tree

megatron/mpu/layers.py
Don't allocate embed LN on pp rank -1, since it's not being used and it just wastes gpu memory if we allocate it.
=> allocate embed norm only on pp0

megatron/mpu/layers.py
as noticed by @thomasw21 - switching embed layernorm to use `MixedFusedLayerNorm` for consistency with other layer norms.
-----------------
Incidentally, this also fixes a bug with how `torch.nn.LayerNorm`  was used until now.
the framework was putting `LayerNorm` into the wrong param group here:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/dd06ea32e014d8db6cdaf5e6839071d6523ca83c/megatron/optimizer/__init__.py#L31-L45
it should have been in `no_weight_decay_params` but ended up in `weight_decay_params` because in this module `LayerNorm` is an alias for `MixedFusedLayerNorm`, so if `isinstance(module_, LayerNorm)` was `False`.
So if we want to use `torch.nn.LayerNorm` we have to change the code above to additionally check for ` or isinstance(module_, …
=> [embed norm] switch to apex MixedFusedLayerNorm

megatron/training.py
while `sys.exit("Exiting")` looks convenient, it exits with an error code rather than 0. so fixing to print the exit message separately.
=> [kill switch] correct sys.exit

megatron/training.py
It's very questionable what this data contributes, other than huge unstripped file paths as keys and hundreds of TB boards that make the TB files very bloated. So disabling for now.
Here is a sample of the current single key: 
`tokens-per-dataset//gpfsscratch/rech/six/commun/bigscience-datasets/merged-meg-ds_v3_pii/ar/bigscience-catalogue-data-dev_byte-level-bpe-tokenizer-no-norm-250k-whitespace-and-eos-regex-alpha-v3-dedup-lines-articles_ar_text_document
tag: tokens-per-dataset//gpfsscratch/rech/six/commun/bigscience-datasets/merged-meg-ds_v3_pii/ar/bigscience-catalogue-data-dev_byte-level-bpe-tokenizer-no-norm-250k-whitespace-and-eos-regex-alpha-v3-dedup-lines-articles_ar_text_document`
Still need to go back and strip this data out of the already existing TB files.
=> [TB] disable samples-per-dataset, steps-per-dataset, tokens-per-dataset

tests/test_training.py
Fixes the test after changing the behavior of kill switch https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/266
=> [kill switch] fix test

megatron/testing_utils.py
looks like pt-1.11 dropped `torch.testing.assert_equal`, so using `torch.testing.assert_close` instead
=> `torch.testing.assert_equal` didn't make it

megatron/data/data_samplers.py
This is in order to start synchronizing the dropout across TP.
=> Make dataloader use another random generator

megatron/fused_kernels/layer_norm_cuda_kernel.cu, megatron/model/fused_layer_norm.py, tests/test_model.py
Above pytorch>=1.11 this makes sense as the cuda kernels allow fp32 accumulation. Also we've "fixed" the `MixedFusedLayerNorm` to do the rescaling operation in float32 before casting.
=> Fix mixed fused layer norm to mimick nn.LayerNorm for torch>1.11

megatron/training.py
From [Efficient Large-Scale Language Model Training on GPU Clusters Using Megatron-LM](https://arxiv.org/pdf/2104.04473.pdf):
> A `𝐴𝑚×𝑘 ×𝑋𝑘×𝑛` matrix multiplication requires `2𝑚 ×𝑘 ×𝑛` FLOPs
> 
> The feed-forward network increases the hidden size to 4ℎ and then reduces it back to ℎ; this requires `16𝐵𝑠ℎ^2` FLOP
We know that
```
Normal
(b, s, h) * (h, h*4)
SwiGLU
(b, s, h) * (h, h*8)
```
Hence
* Normal
`B*(2 * s * h * (h*4)) = b*(8sh^2) = 8bsh^2 -> * 2` for downscaling again -> `16bsh^2` (This turns then into `24𝐵𝑠ℎ^2 + 4𝐵𝑠2ℎ + ...`  with some additional operations, see the paper)
* SwiGLU
`B*(2 * s * h * (h*8)) = b*(16sh^2) = 16bsh^2 (upscaling) + SwiGLU + 8bsh^2 (downscaling) `-> `24bsh^2` (-> We need to add 8, thus `32𝐵𝑠ℎ^2 + 4𝐵𝑠2ℎ + ...`)
I.e. we need to increase the coefficient by 8. …
=> Fix tflops glu computation

megatron/initialize.py
Currently, `deepspeed.comm.get_rank` is called before `deepspeed.init_distributed`, leading to a DS assertion error such as:
`AssertionError: DeepSpeed backend not set, please initialize it using init_process_group()`
If we replace `torch.distributed.init_process_group` with `deepspeed.init_distributed`, DS will both internally call `torch.distributed.init_process_group`, and the DS assertion will pass.
Successfully tested with `make test`
=> Initialize dist with DS

finetune_t0_non_causal_decoder.py, megatron/data/decoder_packed_mtf_dataset.py
This will allow to manually set validation dataset.
=> [MTF] Add `weighted-split-paths` support

scripts/inference/bloom-ds-inference.py
For now requires https://github.com/microsoft/DeepSpeed/pull/2083 to run until it's merged on DS side
=> add OnDevice and remove zero-inference

.github/workflows/main.yml
as there is no active development at the moment disable automatic CI to avoid burning resources while we develop various related scripts which don't use Meg-DS core.
the manual trigger is still enabled if needed to run the CI on demand.
=> disable CI

scripts/bloom-inference-server/README.md, scripts/bloom-inference-server/benchmark.py, scripts/bloom-inference-server/cli.py, scripts/bloom-inference-server/ds_inference/grpc_server.py, scripts/bloom-inference-server/ds_inference/model.py, scripts/bloom-inference-server/ds_zero/model.py, scripts/bloom-inference-server/hf_accelerate/model.py, scripts/bloom-inference-server/server.py, scripts/bloom-inference-server/utils/constants.py, scripts/bloom-inference-server/utils/model.py, scripts/bloom-inference-server/utils/requests.py, scripts/bloom-inference-server/utils/utils.py
@stas00 
This will fix:
1. documentation (currently outdated)
2. fix MII for using DS-inference in server deployments
Let me know if more functionality is desired.
Followup for https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/328
=> Followup PR for adding generation-server

scripts/bloom-inference-scripts/README.md, scripts/bloom-inference-scripts/bloom-accelerate-inference.py, scripts/bloom-inference-scripts/bloom-ds-inference.py, scripts/bloom-inference-scripts/bloom-ds-zero-inference.py
further tweaking of the scripts - updating the stats
=> [bloom inference scripts] improvements
